version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ruh-backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/agent-builder-ui"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/ruh-frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/admin-ui"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/marketplace-ui"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
