export type SkillSource = "clawhub" | "skills_sh" | "custom" | "data_ingestion" | "native_tool" | "existing";
export type SkillNodeStatus =
  | "found"
  | "generating"
  | "generated"
  | "approved"
  | "rejected"
  | "always_included"
  | "pending_approval";

export interface SkillGraphNode {
  skill_id: string;
  name: string;
  source: SkillSource;
  status: SkillNodeStatus;
  depends_on: string[];
  description?: string;
  native_tool?: string | null;
  requires_env?: string[];
  external_api?: string;
  note?: string;
  /** Built SKILL.md content — populated when the skill is built via the wizard. */
  skill_md?: string;
  /** Tool integration type — how the skill connects to external services. */
  tool_type?: "mcp" | "api" | "cli";
  /** MCP registry tool id — only set when tool_type is "mcp". */
  tool_id?: string;
}

export interface WorkflowStep {
  id: string;
  action: string;
  skill: string;
  wait_for: string[];
}

export interface WorkflowDefinition {
  name: string;
  description: string;
  steps: WorkflowStep[];
}

export interface AgentMetadata {
  agent_name?: string;
  agent_id?: string;
  avatar?: string;
  tone?: string;
  domain?: string;
  primary_users?: string;
  automation_type?: string;
  schedule_description?: string;
  cron_expression?: string;
}

export interface AgentRequirements {
  description?: string;
  automation_type?: string;
  data_sources?: Array<{ source_type: string; access_method: string; skill_id?: string }>;
  outputs?: Array<{ type: string; format?: string }>;
  schedule?: string;
  required_env_vars?: string[];
}

export type ToolRecommendationMethod = "mcp" | "api" | "cli";

export interface ToolRecommendationCredential {
  name: string;
  reason: string;
}

export interface ToolRecommendationAlternative {
  method: ToolRecommendationMethod;
  summary: string;
  pros: string[];
  cons: string[];
}

export interface ToolRecommendationSource {
  title: string;
  url: string;
}

export interface ArchitectToolConnection {
  tool_id?: string;
  name?: string;
  description?: string;
  required_env?: string[];
}

export interface ArchitectTrigger {
  id?: string;
  kind?: string;
  title?: string;
  schedule?: string;
  description?: string;
}

export interface ArchitectResponse {
  type:
    | "clarification"
    | "discovery"
    | "ready_for_review"
    | "tool_recommendation"
    | "architecture_plan"
    | "agent_response"
    | "deploy_complete"
    | "build_complete"
    | "error";
  /** Structured discovery questions returned by the architect during intake. */
  discovery_questions?: DiscoveryQuestion[];
  /** PRD/TRD documents generated by the architect during discovery. */
  prd?: DiscoveryDocument;
  trd?: DiscoveryDocument;
  /** Architecture plan generated from PRD/TRD during the Plan stage. */
  architecture_plan?: ArchitecturePlan;
  content?: string;
  questions?: string[];
  // Top-level fields (real architect JSON response)
  system_name?: string;
  description?: string;
  agent_metadata?: AgentMetadata;
  requirements?: AgentRequirements;
  tool_connections?: ArchitectToolConnection[];
  triggers?: ArchitectTrigger[];
  cron_jobs?: Array<{
    name?: string;
    schedule?: string;
    message?: string;
    description?: string;
  }>;
  skill_graph?: {
    system_name?: string; // present only in YAML-normalized path
    nodes: SkillGraphNode[];
    workflow: WorkflowDefinition | { steps: string[] };
    agents?: Array<{ id: string; skills: string[] }>;
  };
  deployment?: { repo_url: string };
  error?: string;
  tool_name?: string;
  recommended_method?: ToolRecommendationMethod;
  recommended_tool_id?: string | null;
  recommended_package?: string;
  summary?: string;
  rationale?: string;
  required_credentials?: ToolRecommendationCredential[];
  setup_steps?: string[];
  integration_steps?: string[];
  validation_steps?: string[];
  alternatives?: ToolRecommendationAlternative[];
  sources?: ToolRecommendationSource[];
  adapter_availability?: Record<
    string,
    { source_type: string; has_adapter: boolean; access_method: string }
  >;
}

// ─── Discovery (copilot intake) ──────────────────────────────────────────────

export type DiscoveryCategory = "use_case" | "channels" | "triggers" | "services" | "audience";

export interface DiscoveryQuestionOption {
  value: string;
  label: string;
  description?: string;
}

export interface DiscoveryQuestion {
  id: string;
  category: DiscoveryCategory;
  question: string;
  type: "select" | "multiselect" | "text";
  options?: DiscoveryQuestionOption[];
  required: boolean;
  defaultValue?: string | string[];
}

// ─── Discovery Documents (PRD + TRD) ────────────────────────────────────────

export interface DiscoveryDocSection {
  heading: string;
  content: string;
}

export interface DiscoveryDocument {
  title: string;
  sections: DiscoveryDocSection[];
}

export interface DiscoveryDocuments {
  prd: DiscoveryDocument;
  trd: DiscoveryDocument;
}

// ─── Agent Development Lifecycle Types ──────────────────────────────────────

export type AgentDevStage = "think" | "plan" | "build" | "review" | "test" | "ship" | "reflect";

export const AGENT_DEV_STAGES: AgentDevStage[] = ["think", "plan", "build", "review", "test", "ship", "reflect"];

export type StageStatus = "idle" | "generating" | "ready" | "approved" | "building" | "running" | "done" | "failed";

// ── Architecture Plan (Plan stage output) ───────────────────────────────────

export interface ArchitecturePlanSkill {
  id: string;
  name: string;
  description: string;
  dependencies: string[];
  externalApi?: string;
  toolType?: "mcp" | "api" | "cli";
  envVars: string[];
}

export interface ArchitecturePlanWorkflow {
  steps: Array<{ skillId: string; parallel: boolean }>;
}

export interface ArchitecturePlanIntegration {
  toolId: string;
  name: string;
  method: "mcp" | "api" | "cli";
  envVars: string[];
}

export interface ArchitecturePlanTrigger {
  id: string;
  type: "cron" | "webhook" | "manual";
  config: string;
  description: string;
}

export interface ArchitecturePlanEnvVar {
  key: string;
  description: string;
  required: boolean;
}

export interface SubAgentConfig {
  id: string;
  name: string;
  description: string;
  type: "worker" | "orchestrator" | "monitor" | "specialist";
  skills: string[];
  trigger: string;
  autonomy: "fully_autonomous" | "requires_approval" | "report_only";
}

export interface MissionControlWidget {
  id: string;
  type: "artifact-feed" | "stats-cards" | "chart" | "table" | "activity-log" | "action-buttons";
  title: string;
  position: { row: number; col: number; width: number; height: number };
  config: Record<string, unknown>;
  dataSource: { endpoint: string; refreshInterval?: number };
}

export interface MissionControlConfig {
  layout: "single-column" | "two-column" | "dashboard-grid";
  widgets: MissionControlWidget[];
}

export interface ArchitecturePlan {
  skills: ArchitecturePlanSkill[];
  workflow: ArchitecturePlanWorkflow;
  integrations: ArchitecturePlanIntegration[];
  triggers: ArchitecturePlanTrigger[];
  channels: string[];
  envVars: ArchitecturePlanEnvVar[];
  subAgents: SubAgentConfig[];
  missionControl: MissionControlConfig | null;
}

// ── Evaluation (Test stage) ─────────────────────────────────────────────────

export type EvalTaskStatus = "pending" | "running" | "pass" | "fail" | "manual";

export interface EvalTask {
  id: string;
  title: string;
  input: string;
  expectedBehavior: string;
  status: EvalTaskStatus;
  response?: string;
  toolsUsed?: string[];
  duration?: number;
  confidence?: number;
  reasons?: string[];
}

// ── Build Report (Reflect stage) ────────────────────────────────────────────

export interface BuildReportStage {
  stage: AgentDevStage;
  status: "completed" | "skipped";
  startedAt?: string;
  completedAt?: string;
  artifacts?: string[];
}

export interface BuildReport {
  agentName: string;
  createdAt: string;
  stages: BuildReportStage[];
  skillCount: number;
  subAgentCount: number;
  integrationCount: number;
  triggerCount: number;
  notes: string;
}

// ── Agent Backend (Artifact + Run) ──────────────────────────────────────────

export type AgentArtifactType = "report" | "data" | "analysis" | "notification" | "log";

export interface AgentArtifact {
  id: string;
  agentId: string;
  runId: string;
  type: AgentArtifactType;
  title: string;
  content: string | Record<string, unknown>;
  metadata: Record<string, unknown>;
  createdAt: string;
}

export type AgentRunTrigger = "cron" | "webhook" | "manual" | "sub-agent";
export type AgentRunStatus = "running" | "completed" | "failed";

export interface AgentRun {
  id: string;
  agentId: string;
  trigger: AgentRunTrigger;
  status: AgentRunStatus;
  startedAt: string;
  completedAt?: string;
  skillsExecuted: string[];
  artifacts: string[];
  logs: string[];
}

export interface ClarificationQuestion {
  id: string;
  question: string;
  type: "text" | "select" | "multiselect" | "boolean";
  placeholder?: string;
  options?: string[];
  required?: boolean;
}

export interface ChatMessage {
  id: string;
  role: "user" | "architect";
  content: string;
  timestamp: string;
  responseType?: ArchitectResponse["type"];
  questions?: ClarificationQuestion[];
  clarificationContext?: string;
}

export interface LifecycleEvent {
  phase: string;
  message: string;
  detail?: string;
}

export type ApprovalDecision = "pending" | "allow" | "deny";

export interface ApprovalEvent {
  approvalId: string;
  toolName: string;
  decision: ApprovalDecision;
  message: string;
  summary?: string;
  justification?: string;
  policyReason?: string;
}
