#!/usr/bin/env python3

from __future__ import annotations

import re
import subprocess
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml
from pypdf import PdfReader


REPO_ROOT = Path(__file__).resolve().parent.parent
VAULT_ROOT = REPO_ROOT / "docs"
KB_ROOT = VAULT_ROOT / "Knowledge Base"
SOURCE_ROOT = VAULT_ROOT / "01 Sources"
GENERATED_MARKER = "<!-- Generated by scripts/sync_obsidian_kb.py. Do not hand-edit. -->"
SUPPORTED_EXTENSIONS = {".pdf", ".docx", ".yaml", ".yml"}
COLLECTION_ORDER = [
    "Platform Core",
    "Reference Packs",
    "Tenant Overlays",
    "Pilot Delivery",
    "Go To Market",
    "Miscellaneous",
]
COLLECTION_MAP_NOTES = [
    "Platform Core",
    "Packs and Overlays",
    "Pilot Delivery",
    "Go To Market",
    "Reading Order",
]
COLLECTION_INTROS = {
    "Platform Core": "The product thesis, system boundary, and reusable pack contract.",
    "Reference Packs": "Reusable operating packs that instantiate the platform for target domains.",
    "Tenant Overlays": "Deployment-specific bindings that map packs into real customer stacks.",
    "Pilot Delivery": "Rollout and proof-of-value material for design-partner deployments.",
    "Go To Market": "Proposal and commercialization material tied to RPX and construction buyers.",
    "Miscellaneous": "Documents that do not match the curated taxonomy yet.",
}
MAP_INTROS = {
    "Platform Core": "Use this map to understand the platform decisions before diving into customer-specific material.",
    "Packs and Overlays": "Use this map to move from reusable pack definitions into deployment-ready overlays and manifests.",
    "Pilot Delivery": "Use this map when you need the rollout path, gate reviews, and pilot operating model.",
    "Go To Market": "Use this map for proposal framing, commercial positioning, and RPX-specific packaging.",
    "Reading Order": "A practical sequence for new readers who need to understand the stack from product thesis to deployable overlays.",
}
MANUAL_METADATA: dict[str, dict[str, Any]] = {
    "RuhAI_Digital_Employee_Platform_PRD": {
        "title": "Digital Employee Platform PRD",
        "aliases": ["Ruh.ai Platform Product Requirements Document"],
        "artifact_type": "platform-prd",
        "collection": "Platform Core",
        "domain": "platform",
        "summary": "Defines Ruh.ai as a horizontal digital employee operating system built on OpenClaw, including the core product thesis, trust-boundary model, and go-to-market shape.",
        "status": "Internal draft v1.0",
    },
    "RuhAI_V1_System_Design_MVP_Execution_Blueprint": {
        "title": "System Design and MVP Execution Blueprint",
        "aliases": ["RUH.AI V1 System Design & MVP Execution Blueprint"],
        "artifact_type": "system-design",
        "collection": "Platform Core",
        "domain": "platform",
        "summary": "Translates the PRD into a V1 architecture, control-plane/runtime split, collaboration model, and phased implementation sequence.",
        "status": "Working draft",
    },
    "RuhAI_V1_Employee_Pack_Specification": {
        "title": "Employee Pack Specification",
        "aliases": ["Ruh.ai V1 Employee Pack Specification"],
        "artifact_type": "pack-spec",
        "collection": "Platform Core",
        "domain": "platform",
        "summary": "Defines the reusable pack format, validation rules, deployment lifecycle, and governance contract for digital employees.",
        "status": "Working draft v1.0",
    },
    "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps": {
        "title": "AI BuildOps Reference Pack",
        "aliases": ["Ruh.ai V1 Reference Pack Definition AI BuildOps Pack"],
        "artifact_type": "reference-pack",
        "collection": "Reference Packs",
        "domain": "ai-buildops",
        "summary": "Instantiates the platform for AI product teams, covering intake, spec quality, implementation flow, eval gating, release, and incident learning.",
        "status": "Internal working document",
    },
    "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations": {
        "title": "Construction Project Operations Reference Pack",
        "aliases": ["Ruh.ai V1 Reference Pack Definition Construction Project Operations Pack"],
        "artifact_type": "reference-pack",
        "collection": "Reference Packs",
        "domain": "construction",
        "summary": "Instantiates the platform for construction operations workflows such as RFIs, submittals, reporting, and meeting-action coordination.",
        "status": "Internal working document",
    },
    "RuhAI_V1_Tenant_Overlay_Kit_AI_BuildOps_GitHub_Linear_Slack_Sentry": {
        "title": "AI BuildOps Tenant Overlay Kit",
        "aliases": ["Ruh.ai V1 Tenant Overlay Kit AI BuildOps - GitHub + Linear + Slack + Sentry"],
        "artifact_type": "overlay-kit",
        "collection": "Tenant Overlays",
        "domain": "ai-buildops",
        "summary": "Maps the reusable AI BuildOps pack into a GitHub, Linear, Slack, and Sentry operating stack for pilot and first-production use.",
        "status": "Version 0.1.0",
    },
    "ai-buildops.github-linear-slack-sentry.overlay": {
        "title": "AI BuildOps Overlay Manifest",
        "aliases": ["ai-buildops.github-linear-slack-sentry overlay"],
        "artifact_type": "overlay-manifest",
        "collection": "Tenant Overlays",
        "domain": "ai-buildops",
        "summary": "Machine-readable tenant overlay manifest for the AI BuildOps deployment, including trust boundary, connectors, workflows, and approval policies.",
        "status": "Version 0.1.0",
    },
    "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams": {
        "title": "Construction Tenant Overlay Kit",
        "aliases": ["Ruh.ai V1 Tenant Overlay Kit Construction Project Operations - Procore + SharePoint + Teams"],
        "artifact_type": "overlay-kit",
        "collection": "Tenant Overlays",
        "domain": "construction",
        "summary": "Maps the construction operations pack into a Procore, SharePoint, and Teams stack for project-scoped pilot and early production use.",
        "status": "Version 0.1.0",
    },
    "construction.procore-sharepoint-teams.overlay": {
        "title": "Construction Overlay Manifest",
        "aliases": ["construction.procore-sharepoint-teams overlay"],
        "artifact_type": "overlay-manifest",
        "collection": "Tenant Overlays",
        "domain": "construction",
        "summary": "Machine-readable tenant overlay manifest for construction operations, including project workspace topology, workflows, and approval mappings.",
        "status": "Version 0.1.0",
    },
    "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook": {
        "title": "Design Partner Pilot Blueprint and Rollout Runbook",
        "aliases": ["RUH.AI V1 Design Partner Pilot Blueprint & Rollout Runbook"],
        "artifact_type": "pilot-runbook",
        "collection": "Pilot Delivery",
        "domain": "cross-pack",
        "summary": "Defines the repeatable pilot model, qualification gates, rollout phases, and scorecards for proving digital employees with real customers.",
        "status": "Working v1 execution document",
    },
    "RPXTech_AI_Business_Proposal": {
        "title": "RPXTech AI Business Proposal",
        "aliases": ["RPX Technologies Business Proposal"],
        "artifact_type": "proposal",
        "collection": "Go To Market",
        "domain": "rpx",
        "summary": "Frames a proposal for launching InSite AI powered by Ruh.ai on top of RPX's existing concrete-monitoring footprint.",
        "status": "Prepared March 6, 2026",
    },
    "RuhAI_Construction_Proposal_for_RPX": {
        "title": "Construction Proposal for RPX",
        "aliases": ["RUH.AI Construction Digital Employees Proposal for RPX Construction"],
        "artifact_type": "proposal",
        "collection": "Go To Market",
        "domain": "rpx",
        "summary": "Makes the case for a horizontal construction solution built from reusable digital employees and positions RPX as both buyer and future partner.",
        "status": "Prepared for strategic discussion",
    },
}
RELATED_DOCUMENTS: dict[str, list[str]] = {
    "RuhAI_Digital_Employee_Platform_PRD": [
        "RuhAI_V1_System_Design_MVP_Execution_Blueprint",
        "RuhAI_V1_Employee_Pack_Specification",
        "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    ],
    "RuhAI_V1_System_Design_MVP_Execution_Blueprint": [
        "RuhAI_Digital_Employee_Platform_PRD",
        "RuhAI_V1_Employee_Pack_Specification",
        "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    ],
    "RuhAI_V1_Employee_Pack_Specification": [
        "RuhAI_Digital_Employee_Platform_PRD",
        "RuhAI_V1_System_Design_MVP_Execution_Blueprint",
        "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps",
        "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
    ],
    "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps": [
        "RuhAI_V1_Employee_Pack_Specification",
        "RuhAI_V1_Tenant_Overlay_Kit_AI_BuildOps_GitHub_Linear_Slack_Sentry",
        "ai-buildops.github-linear-slack-sentry.overlay",
        "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    ],
    "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations": [
        "RuhAI_V1_Employee_Pack_Specification",
        "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams",
        "construction.procore-sharepoint-teams.overlay",
        "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    ],
    "RuhAI_V1_Tenant_Overlay_Kit_AI_BuildOps_GitHub_Linear_Slack_Sentry": [
        "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps",
        "ai-buildops.github-linear-slack-sentry.overlay",
        "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    ],
    "ai-buildops.github-linear-slack-sentry.overlay": [
        "RuhAI_V1_Tenant_Overlay_Kit_AI_BuildOps_GitHub_Linear_Slack_Sentry",
        "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps",
    ],
    "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams": [
        "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
        "construction.procore-sharepoint-teams.overlay",
        "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    ],
    "construction.procore-sharepoint-teams.overlay": [
        "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams",
        "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
    ],
    "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook": [
        "RuhAI_Digital_Employee_Platform_PRD",
        "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps",
        "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
    ],
    "RPXTech_AI_Business_Proposal": [
        "RuhAI_Construction_Proposal_for_RPX",
        "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
        "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams",
    ],
    "RuhAI_Construction_Proposal_for_RPX": [
        "RPXTech_AI_Business_Proposal",
        "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
        "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams",
    ],
}
READING_ORDER = [
    "RuhAI_Digital_Employee_Platform_PRD",
    "RuhAI_V1_System_Design_MVP_Execution_Blueprint",
    "RuhAI_V1_Employee_Pack_Specification",
    "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps",
    "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
    "RuhAI_V1_Tenant_Overlay_Kit_AI_BuildOps_GitHub_Linear_Slack_Sentry",
    "ai-buildops.github-linear-slack-sentry.overlay",
    "RuhAI_V1_Tenant_Overlay_Kit_Construction_Procore_SharePoint_Teams",
    "construction.procore-sharepoint-teams.overlay",
    "RuhAI_V1_Design_Partner_Pilot_Blueprint_and_Rollout_Runbook",
    "RPXTech_AI_Business_Proposal",
    "RuhAI_Construction_Proposal_for_RPX",
]


@dataclass
class SourceVariant:
    path: Path
    extension: str
    preview: str
    extracted_title: str | None = None
    page_count: int | None = None
    yaml_data: dict[str, Any] | None = None


@dataclass
class DocumentRecord:
    key: str
    title: str
    aliases: list[str]
    artifact_type: str
    collection: str
    domain: str
    summary: str
    status: str | None
    note_path: Path
    note_link: str
    variants: list[SourceVariant]
    related_keys: list[str]


def clean_text(value: str) -> str:
    value = value.replace("\x0c", "\n")
    value = value.replace("\r", "\n")
    value = re.sub(r"[ \t]+", " ", value)
    value = re.sub(r"\n{3,}", "\n\n", value)
    return value.strip()


def truncate(value: str, limit: int) -> str:
    value = value.strip()
    if len(value) <= limit:
        return value
    return value[: limit - 3].rstrip() + "..."


def slugify(name: str) -> str:
    name = name.replace("&", "and")
    name = re.sub(r"[<>:\"/\\\\|?*]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def prettify_stem(stem: str) -> str:
    parts = re.split(r"[_.-]+", stem)
    words = []
    for part in parts:
        if not part:
            continue
        if part.isupper() or any(char.isdigit() for char in part):
            words.append(part)
        else:
            words.append(part.capitalize())
    return " ".join(words)


def derive_artifact_type(stem: str) -> str:
    if "PRD" in stem:
        return "platform-prd"
    if "System_Design" in stem:
        return "system-design"
    if "Pack_Specification" in stem:
        return "pack-spec"
    if "Reference_Pack_Definition" in stem:
        return "reference-pack"
    if "Tenant_Overlay_Kit" in stem:
        return "overlay-kit"
    if stem.endswith(".overlay"):
        return "overlay-manifest"
    if "Runbook" in stem or "Blueprint" in stem:
        return "pilot-runbook"
    if "Proposal" in stem:
        return "proposal"
    return "document"


def derive_collection(artifact_type: str) -> str:
    if artifact_type in {"platform-prd", "system-design", "pack-spec"}:
        return "Platform Core"
    if artifact_type == "reference-pack":
        return "Reference Packs"
    if artifact_type in {"overlay-kit", "overlay-manifest"}:
        return "Tenant Overlays"
    if artifact_type == "pilot-runbook":
        return "Pilot Delivery"
    if artifact_type == "proposal":
        return "Go To Market"
    return "Miscellaneous"


def derive_domain(stem: str) -> str:
    lower = stem.lower()
    if "construction" in lower or "procore" in lower or "sharepoint" in lower or "teams" in lower:
        return "construction"
    if "buildops" in lower or "github" in lower or "linear" in lower or "sentry" in lower:
        return "ai-buildops"
    if "rpx" in lower:
        return "rpx"
    return "platform"


def extract_status(preview: str) -> str | None:
    patterns = [
        r"Status[: ]+([A-Za-z0-9.\- ]{4,60})",
        r"Document status[: ]+([A-Za-z0-9.\- |]{4,60})",
        r"VERSION[: ]+([A-Za-z0-9.\- ]{3,30})",
    ]
    for pattern in patterns:
        match = re.search(pattern, preview, flags=re.IGNORECASE)
        if match:
            return clean_text(match.group(1))
    return None


def summarize_preview(preview: str) -> str:
    sentences = re.split(r"(?<=[.!?])\s+", clean_text(preview))
    selected: list[str] = []
    for sentence in sentences:
        sentence = sentence.strip()
        if not sentence:
            continue
        selected.append(sentence)
        if len(" ".join(selected)) >= 280 or len(selected) >= 2:
            break
    if not selected:
        return "Generated from the source file inventory."
    return truncate(" ".join(selected), 320)


def discover_source_groups() -> dict[str, list[Path]]:
    groups: dict[str, list[Path]] = {}
    for path in sorted(SOURCE_ROOT.rglob("*")):
        if not path.is_file():
            continue
        if path.name.startswith("."):
            continue
        if path.suffix.lower() not in SUPPORTED_EXTENSIONS:
            continue
        groups.setdefault(path.stem, []).append(path)
    return groups


def extract_docx_variant(path: Path) -> SourceVariant:
    try:
        result = subprocess.run(
            ["textutil", "-convert", "txt", "-stdout", str(path)],
            check=True,
            capture_output=True,
            text=True,
        )
        preview = clean_text(result.stdout)
    except subprocess.CalledProcessError:
        preview = ""
    title = preview.splitlines()[0].strip() if preview else None
    return SourceVariant(path=path, extension=".docx", preview=truncate(preview, 1600), extracted_title=title)


def extract_pdf_variant(path: Path) -> SourceVariant:
    preview_chunks: list[str] = []
    page_count: int | None = None
    extracted_title: str | None = None
    try:
        reader = PdfReader(str(path))
        page_count = len(reader.pages)
        if getattr(reader, "metadata", None):
            extracted_title = getattr(reader.metadata, "title", None)
        for page in reader.pages[:2]:
            page_text = clean_text(page.extract_text() or "")
            if page_text:
                preview_chunks.append(page_text)
            if len(" ".join(preview_chunks)) >= 1800:
                break
    except Exception:
        pass
    preview = truncate(" ".join(preview_chunks), 1600)
    return SourceVariant(
        path=path,
        extension=".pdf",
        preview=preview,
        extracted_title=extracted_title,
        page_count=page_count,
    )


def extract_yaml_variant(path: Path) -> SourceVariant:
    raw = path.read_text(encoding="utf-8")
    data = yaml.safe_load(raw) or {}
    preview = clean_text(raw)
    title = None
    metadata = data.get("metadata", {})
    if isinstance(metadata, dict):
        title = metadata.get("displayName") or metadata.get("overlayId")
    return SourceVariant(
        path=path,
        extension=path.suffix.lower(),
        preview=truncate(preview, 1600),
        extracted_title=title,
        yaml_data=data if isinstance(data, dict) else None,
    )


def extract_variant(path: Path) -> SourceVariant:
    extension = path.suffix.lower()
    if extension == ".docx":
        return extract_docx_variant(path)
    if extension == ".pdf":
        return extract_pdf_variant(path)
    return extract_yaml_variant(path)


def pick_primary_variant(variants: list[SourceVariant]) -> SourceVariant:
    priority = {".docx": 0, ".pdf": 1, ".yaml": 2, ".yml": 2}
    return sorted(variants, key=lambda variant: priority.get(variant.extension, 10))[0]


def build_note_link(relative_path: Path, title: str) -> str:
    target = relative_path.with_suffix("").as_posix()
    return f"[[{target}|{title}]]"


def yaml_snapshot_lines(data: dict[str, Any] | None) -> list[str]:
    if not data:
        return []
    metadata = data.get("metadata", {}) if isinstance(data, dict) else {}
    connectors = data.get("connectors", {}) if isinstance(data, dict) else {}
    workflows = data.get("workflows", {}) if isinstance(data, dict) else {}
    trust_boundary = data.get("trustBoundary", {}) if isinstance(data, dict) else {}
    lines: list[str] = []
    if isinstance(metadata, dict):
        if metadata.get("overlayId"):
            lines.append(f"- Overlay ID: `{metadata['overlayId']}`")
        if metadata.get("packRef"):
            lines.append(f"- Pack reference: `{metadata['packRef']}`")
        if metadata.get("owner"):
            lines.append(f"- Owner: `{metadata['owner']}`")
        if metadata.get("displayName"):
            lines.append(f"- Display name: {metadata['displayName']}")
    if isinstance(trust_boundary, dict) and trust_boundary.get("key"):
        lines.append(f"- Trust boundary: `{trust_boundary['key']}`")
    if isinstance(connectors, dict) and connectors:
        connector_names = ", ".join(f"`{name}`" for name in sorted(connectors))
        lines.append(f"- Connectors: {connector_names}")
    if isinstance(workflows, dict) and workflows:
        workflow_names = ", ".join(f"`{name}`" for name in sorted(workflows))
        lines.append(f"- Workflows: {workflow_names}")
    return lines


def build_frontmatter(record: DocumentRecord, relative_sources: list[str]) -> str:
    frontmatter = {
        "aliases": record.aliases,
        "type": "kb/document",
        "collection": record.collection.lower().replace(" ", "-"),
        "artifact_type": record.artifact_type,
        "domain": record.domain,
        "generated": True,
        "source_files": relative_sources,
        "tags": [
            "kb/document",
            f"collection/{record.collection.lower().replace(' ', '-')}",
            f"artifact/{record.artifact_type}",
            f"domain/{record.domain}",
        ],
    }
    return "---\n" + yaml.safe_dump(frontmatter, sort_keys=False, allow_unicode=False).strip() + "\n---"


def build_document_note(record: DocumentRecord, note_lookup: dict[str, DocumentRecord]) -> str:
    relative_sources = [variant.path.relative_to(VAULT_ROOT).as_posix() for variant in record.variants]
    sections = [
        build_frontmatter(record, relative_sources),
        GENERATED_MARKER,
        f"# {record.title}",
        "",
        "## Summary",
        record.summary,
        "",
        "## Source Files",
    ]

    for variant in sorted(record.variants, key=lambda item: item.extension):
        relative = Path(os.path.relpath(variant.path, start=record.note_path.parent)).as_posix()
        details = [variant.extension.replace(".", "").upper()]
        if variant.page_count:
            details.append(f"{variant.page_count} pages")
        sections.append(f"- [{variant.path.name}]({relative}) ({', '.join(details)})")

    sections.extend(["", "## Snapshot"])
    sections.append(f"- Collection: {record.collection}")
    sections.append(f"- Artifact type: `{record.artifact_type}`")
    sections.append(f"- Domain: `{record.domain}`")
    if record.status:
        sections.append(f"- Status: {record.status}")
    sections.append(
        "- Formats: " + ", ".join(variant.extension.replace(".", "").upper() for variant in sorted(record.variants, key=lambda item: item.extension))
    )

    primary = pick_primary_variant(record.variants)
    if primary.yaml_data:
        yaml_lines = yaml_snapshot_lines(primary.yaml_data)
        if yaml_lines:
            sections.extend(["", "## Manifest Highlights", *yaml_lines])

    related_links = [
        note_lookup[key].note_link
        for key in record.related_keys
        if key in note_lookup and key != record.key
    ]
    if related_links:
        sections.extend(["", "## Related Notes"])
        sections.extend(f"- {link}" for link in related_links)

    if primary.preview:
        sections.extend(["", "## Extracted Preview", f"> {primary.preview.replace(chr(10), chr(10) + '> ')}"])

    sections.append("")
    return "\n".join(sections)


def sort_records(records: list[DocumentRecord]) -> list[DocumentRecord]:
    collection_order = {name: index for index, name in enumerate(COLLECTION_ORDER)}
    return sorted(records, key=lambda record: (collection_order.get(record.collection, 99), record.title.lower()))


def build_map_note(name: str, records: list[DocumentRecord], note_lookup: dict[str, DocumentRecord]) -> str:
    lines = [GENERATED_MARKER, f"# {name}", "", MAP_INTROS[name], ""]

    if name == "Platform Core":
        subset = [record for record in records if record.collection == "Platform Core"]
        lines.append("## Core Documents")
        lines.extend(f"- {record.note_link} - {record.summary}" for record in subset)
    elif name == "Packs and Overlays":
        for domain in ("ai-buildops", "construction"):
            label = "AI BuildOps" if domain == "ai-buildops" else "Construction"
            lines.extend(["", f"## {label}"])
            subset = [
                record
                for record in records
                if record.domain == domain and record.collection in {"Reference Packs", "Tenant Overlays"}
            ]
            lines.extend(f"- {record.note_link} - {record.summary}" for record in subset)
    elif name == "Pilot Delivery":
        subset = [record for record in records if record.collection == "Pilot Delivery"]
        lines.append("## Rollout Material")
        lines.extend(f"- {record.note_link} - {record.summary}" for record in subset)
        lines.extend(["", "## Related Platform Context"])
        for key in [
            "RuhAI_Digital_Employee_Platform_PRD",
            "RuhAI_V1_Reference_Pack_Definition_AI_BuildOps",
            "RuhAI_V1_Reference_Pack_Definition_Construction_Project_Operations",
        ]:
            if key in note_lookup:
                lines.append(f"- {note_lookup[key].note_link}")
    elif name == "Go To Market":
        subset = [record for record in records if record.collection == "Go To Market"]
        lines.append("## Proposal Material")
        lines.extend(f"- {record.note_link} - {record.summary}" for record in subset)
    elif name == "Reading Order":
        lines.append("## Recommended Sequence")
        for index, key in enumerate(READING_ORDER, start=1):
            if key in note_lookup:
                lines.append(f"{index}. {note_lookup[key].note_link} - {note_lookup[key].summary}")

    lines.append("")
    return "\n".join(lines)


def build_document_library(records: list[DocumentRecord]) -> str:
    lines = [
        GENERATED_MARKER,
        "# Document Library",
        "",
        "Canonical document index for the vault. Each note groups all source-file variants for the same document.",
        "",
        "| Document | Collection | Domain | Formats | Source Files |",
        "| --- | --- | --- | --- | --- |",
    ]
    for record in sort_records(records):
        formats = ", ".join(variant.extension.replace(".", "").upper() for variant in sorted(record.variants, key=lambda item: item.extension))
        source_count = f"{len(record.variants)} file{'s' if len(record.variants) != 1 else ''}"
        lines.append(f"| {record.note_link} | {record.collection} | `{record.domain}` | {formats} | {source_count} |")
    lines.append("")
    return "\n".join(lines)


def build_source_inventory(records: list[DocumentRecord]) -> str:
    lines = [
        GENERATED_MARKER,
        "# Source Inventory",
        "",
        "Raw source files under `01 Sources/`, mapped back to their knowledge-base notes.",
        "",
    ]
    for record in sort_records(records):
        lines.append(f"## {record.title}")
        lines.append(f"- Note: {record.note_link}")
        for variant in sorted(record.variants, key=lambda item: item.extension):
            relative = variant.path.relative_to(VAULT_ROOT).as_posix()
            detail = variant.extension.replace(".", "").upper()
            if variant.page_count:
                detail += f", {variant.page_count} pages"
            lines.append(f"- Source: [{variant.path.name}](../../{relative}) ({detail})")
        lines.append("")
    return "\n".join(lines)


def build_home_note(records: list[DocumentRecord]) -> str:
    lines = [
        GENERATED_MARKER,
        "# Ruh.ai Knowledge Base",
        "",
        "This vault uses `docs` as the Obsidian root. Raw source material lives under `01 Sources/`, operational assets live under `02 Operations/`, and generated knowledge notes live under `Knowledge Base/`.",
        "",
        "## Project Knowledge",
        "- [[Knowledge Base/Project Knowledge/Project Knowledge Hub|Project Knowledge Hub]]",
        "- [[Knowledge Base/Project Knowledge/Project Brief|Project Brief]]",
        "- [[Knowledge Base/Project Knowledge/Architecture Model|Architecture Model]]",
        "- [[Knowledge Base/Project Knowledge/Packs and Overlays|Packs and Overlays]]",
        "- [[Knowledge Base/Project Knowledge/Delivery Model|Delivery Model]]",
        "- [[Knowledge Base/Project Knowledge/Commercial Context|Commercial Context]]",
        "- [[Knowledge Base/Project Knowledge/Glossary|Glossary]]",
        "- [[Knowledge Base/Project Knowledge/Open Questions|Open Questions]]",
        "- [[02 Operations/Linear/README|Linear Planning]]",
        "- [[01 Sources/README|Source Library]]",
        "",
        "## Start Here",
        "- [[Knowledge Base/Maps/Platform Core|Platform Core]]",
        "- [[Knowledge Base/Maps/Packs and Overlays|Packs and Overlays]]",
        "- [[Knowledge Base/Maps/Pilot Delivery|Pilot Delivery]]",
        "- [[Knowledge Base/Maps/Go To Market|Go To Market]]",
        "- [[Knowledge Base/Maps/Reading Order|Reading Order]]",
        "- [[Knowledge Base/Indexes/Document Library|Document Library]]",
        "- [[Knowledge Base/Indexes/Source Inventory|Source Inventory]]",
        "",
        "## Vault Conventions",
        "- `01 Sources/` contains the raw PDFs, DOCX files, and YAML manifests organized by source class.",
        "- `02 Operations/` contains working assets such as Linear planning material.",
        "- `Knowledge Base/Documents/` contains generated canonical notes for each document family.",
        "- `Knowledge Base/Project Knowledge/` contains curated synthesis notes for fast project understanding.",
        "- `99 Inbox/` is the default folder for new working notes.",
        "- `98 Templates/` contains templates for manual notes you add in Obsidian.",
        "- The raw files under `01 Sources/` remain the source of truth.",
        "",
        "## Refresh The Generated Knowledge Base",
        "Run one of these commands whenever the `docs` folder changes:",
        "",
        "```bash",
        "python3 scripts/sync_obsidian_kb.py",
        "```",
        "",
        "or, if your shell is already inside `docs/`:",
        "",
        "```bash",
        "python3 ../scripts/sync_obsidian_kb.py",
        "```",
        "",
        "## Current Coverage",
        f"- Canonical documents: {len(records)}",
        f"- Source files tracked: {sum(len(record.variants) for record in records)}",
        "",
    ]
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def build_records() -> list[DocumentRecord]:
    groups = discover_source_groups()
    records: list[DocumentRecord] = []
    for key, paths in sorted(groups.items()):
        variants = [extract_variant(path) for path in sorted(paths)]
        primary = pick_primary_variant(variants)
        manual = MANUAL_METADATA.get(key, {})
        title = manual.get("title") or primary.extracted_title or prettify_stem(key)
        aliases = manual.get("aliases") or ([primary.extracted_title] if primary.extracted_title and primary.extracted_title != title else [])
        artifact_type = manual.get("artifact_type") or derive_artifact_type(key)
        collection = manual.get("collection") or derive_collection(artifact_type)
        domain = manual.get("domain") or derive_domain(key)
        summary = manual.get("summary") or summarize_preview(primary.preview)
        status = manual.get("status") or extract_status(primary.preview)
        filename = slugify(title) + ".md"
        relative_note_path = Path("Knowledge Base") / "Documents" / collection / filename
        note_path = VAULT_ROOT / relative_note_path
        note_link = build_note_link(relative_note_path, title)
        related_keys = RELATED_DOCUMENTS.get(key, [])
        records.append(
            DocumentRecord(
                key=key,
                title=title,
                aliases=aliases,
                artifact_type=artifact_type,
                collection=collection,
                domain=domain,
                summary=summary,
                status=status,
                note_path=note_path,
                note_link=note_link,
                variants=variants,
                related_keys=related_keys,
            )
        )
    return records


def main() -> None:
    if not VAULT_ROOT.exists():
        raise SystemExit(f"Vault root does not exist: {VAULT_ROOT}")

    records = build_records()
    lookup = {record.key: record for record in records}

    for record in records:
        write_if_changed(record.note_path, build_document_note(record, lookup))

    map_root = KB_ROOT / "Maps"
    for name in COLLECTION_MAP_NOTES:
        write_if_changed(map_root / f"{name}.md", build_map_note(name, sort_records(records), lookup))

    indexes_root = KB_ROOT / "Indexes"
    write_if_changed(indexes_root / "Document Library.md", build_document_library(records))
    write_if_changed(indexes_root / "Source Inventory.md", build_source_inventory(records))
    write_if_changed(VAULT_ROOT / "Home.md", build_home_note(records))

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"Synced Obsidian knowledge base at {generated_at}")
    print(f"Canonical documents: {len(records)}")
    print(f"Source files tracked: {sum(len(record.variants) for record in records)}")


if __name__ == "__main__":
    main()
